Neos:
  Neos:
    fusion:
      autoInclude:
        Litefyr.Templates: true
    userInterface:
      translation:
        autoInclude:
          Litefyr.Templates:
            - 'NodeTypes/*'
  Fusion:
    defaultContext:
      Litefyr.Templates: 'Litefyr\Templates\Eel\SettingsHelper'
